spring.application.name=cartflame
spring.datasource.url=jdbc:postgresql://localhost:5432/cartflame
spring.datasource.username=deniz
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=rRpsvo+Sd0/bnNS6nzi5WCOK9GrWu/9JI3nZ3YRGuEI=
jwt.expiration-ms=604800000