spring.application.name=cartflame
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cartflame}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:deniz}
spring.datasource.password=${DATABASE_PASSWORD}

# i use update here because
# it is really fast for development environment
# ATTENTION IF YOU EVER GO TO PRODUCTION
# REMOVE UPDATE
spring.jpa.hibernate.ddl-auto=update

# i don't want this spring.jpa.show-sql to be on
# because it REALLY pollutes logs
spring.jpa.show-sql=false
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=604800000

spring.jpa.open-in-view=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dnzdyn2012@gmail.com
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
# timeout in milliseconds
spring.rabbitmq.connection-timeout=15000
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# auto recovery
spring.rabbitmq.simple.prefetch=10

# redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}